### ISSUE TITLE
Pass MF2WG string test #02

### ISSUE THREAD

**Issue by mvilks** [translate-agent/mf2#135]
A MF2WG string function test
```json
    {
      "src": ".match {$foo :string} 1 {{one}} * {{other}}",
      "exp": "other",
      "expErrors": [
        {
          "type": "unresolved-variable"
        }
      ]
    }
```
fails with `want other, got `--return value is not calculated when error is thrown.

**Comment by janishorsts** [comment]
According to the [MF2 spec](https://github.com/unicode-org/message-format-wg/blob/main/spec/errors.md#error-handling)

> When an error occurs within a selector,
> the selector MUST NOT match any variant key other than the catch-all *
> and a Resolution Error or a Message Function Error MUST be emitted.`
