### ISSUE TITLE
Data model errors

### ISSUE THREAD

**Issue by mvilks** [translate-agent/mf2#240]
Currently, there are two places where different [data model errors](https://github.com/unicode-org/message-format-wg/blob/main/spec/errors.md#data-model-errors) are being emitted: `parse.go` and `template.go`. Parser emits `variant-key-mismatch` and `missing-fallback-variant`, the template executor emits the rest.

Would it be wise to move them all to one place - either into parser or into template executor?

**Comment by janishorsts** [comment]
|error|package|
|-----|-----|
|Variant Key Mismatch|parse|
|Missing Fallback Variant|parse|
|Missing Selector Annotation|template|
|Duplicate Declaration|parse|
|Duplicate Option Name|template|
|Duplicate Variant|template|
